apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: external-secrets-config
    helm:
      releaseName: external-secrets-config
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
