env: dev

database:
  secretPath: taskapp/dev/database

backend:
  awsCredentialsEnabled: true
  awsCredentialsSecretPath: taskapp/dev/backend-credentials
  sqsEnabled: false
  sqsQueueUrl: ""
  sqsRegion: eu-west-1
