env: prod

destinationServer: "https://192.168.58.2:8443"

database:
  secretPath: taskapp/prod/database

backend:
  awsCredentialsEnabled: true
  awsCredentialsSecretPath: taskapp/prod/backend-credentials
  sqsEnabled: true
  sqsQueueUrl: "https://sqs.eu-west-1.amazonaws.com/425832464758/taskapp-prod-tasks"
  sqsRegion: eu-west-1
  kedaEnabled: true
